### PR TITLE
[Fix]: Don't log image data to traces in Bedrock and OpenAI Instrumentors

### PR DESCRIPTION
**Pull request by chriskhanhtran**
### Overview:
This PR addresses 2 issues:
- #501: in bedrock instrumentor, fix bug for message containing image content
- #502: in openai instrumentor, do not log image_url if it's base64 encoded image data

### Checklist:
- [x] PR name follows conventional commit format: `[Feat]: ...` or `[Fix]: ....`
- [x] Added visuals for changes (If applicable)
- [x] Checked OpenLIT [contribution guidelines](https://github.com/openlit/openlit/blob/main/CONTRIBUTING.md)

## Summary by Sourcery

Fix bugs in Bedrock and OpenAI instrumentors to prevent logging of image data, ensuring that only non-base64 encoded image URLs are logged.

Bug Fixes:
- Fix issue in Bedrock instrumentor where messages containing image content were incorrectly logged.
- Prevent logging of base64 encoded image data in OpenAI instrumentor by checking the image URL format.

### CODE REVIEW

**Comment by chriskhanhtran** [comment]
@patcher9  I fixed Bedrock and OpenAI instrumentors to not log image or image_url if it's base64 encoded image. However, I believe that this issue might be present in other instrumentors, for which I either don't use or don't know how to address the issue of logging image data to traces.

**Comment by amanagarwal042** [comment]
Perfect! I am out today (Thanksgiving in the US) but I will take a look early tomorrow. That works?

**Comment by amanagarwal042** [comment]
Can you bump the version in pyproject.toml to `1.32.6`

**Comment by amanagarwal042** [comment]
Changes LGTM, Just a couple pylint fixes you'd need to make before I can merge

**Review by amanagarwal042 — APPROVED** [review]

**Pull request merged**
